# Configuration for the server
server:
  # Port number the server listens on
  listen_port: 10086
  # Authentication key for API access
  api_auth: "your_api_auth_key"

# Configuration for logging
log:
  # Maximum size of log files in MB
  max_size: 50
  # Maximum number of backup log files to keep
  max_backups: 3
  # Maximum age of log files in days
  max_age: 30

sqlite:
  # Path to the SQLite database file
  dsn: "/Users/chenming/Desktop/my_database.db"